language: python
python:
  - '3.5'
  - '3.8'
addons:
  apt:
    packages:
    - libav-tools
install:
  - python setup.py sdist --formats=zip -k
  - find ./dist -iname "*.zip" -print0 | xargs -0 pip install
  - wget https://gist.github.com/simon-weber/8211306/raw/travis-secure-redefine.py
  - pip install flake8==2.4.0
before_script:
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then export GROUP='--group=local'; fi
script:
  - flake8 example.py setup.py gmusicapi
  - python travis-secure-redefine.py "python -m gmusicapi.test.run_tests $GROUP" IDARG GM_R GM_O GM_I GM_A
after_failure: cat `python -c 'from __future__ import print_function; from gmusicapi.utils import utils; print(utils.log_filepath)'`
branches:
  only:
  - develop
  - master
env:
  global:
  - GM_N="Travis-CI (gmusicapi)"
  - GM_AA_D_ID="ios:96BCE7FD-4C0B-4B11-883A-2FCF534AC99C"
    # AA: r, o, i, a
    # append 1 to vars
  - secure: "PmgQB0jQlh2FZU1z3BORvPuYLp4dVQeiWs7f9605Xt/yCqnbEtq0AssAQc3oODYLP5ra261wRGOIuFQNNVIrtgWPzsEirS2grEAqgwvohhmWLhRGOgNDsg9TTv91k54bMj1QEGbBDatNLANHuKJgHSOWy70HYnIEabydxGeiuhQ="
  - secure: "AI726k373fAUBgZPRWrZ1BzpFnGhJDJcmopwb9I5R8Jl1Mt2zYHEuVXk7b00oCoa8Q8smMoG8OvTQZEEO/1pna0M61vvx5MIR257Zct5+9fREh8kv8HYFScrndNTDuvRtijMJtOKhfeI9XiQnzuHavgveXBMHtQvxZTnVm77RlE="
  - secure: cQ/KaEOW73kmT5NwvQnT+H3w0yMtxhJWvBCnGahzmYMUlr7UjW5XkF4FpYiLX0MfKYbPLIIxGe7knwNznbFEGPjwwYhsQjhgikY+ufvF5l3VN2zvC04QjD3SWTz3oYGdhQSHakbMwRT+UFkQPXswZ+dxp3DsqD253eVNmybgn9c=
  - secure: QYItohH4sbVkSFKBpKUQl+a4ONMJjNHg/YIyDpLkVh68qBuJ2ZiT1ufjD9drt4a2K/hyD2wmnwvovcM6kXJiFdLsEIthJG8gW7GUyIzXQZMH85dfl8BUBqY/JPUNiRibX8JYxxkz3e6QKq6uQ0NIc1Df6P10IJib3ZdXw94ybSg=
    # non-AA: r, o, i
    # append 2 to vars
  - secure: "gFlhkNjlGZgnM6Yj5mX3CWogvczmW4IMmmeQFf7X1WuErF7xpx5QkuVQZoGZ/SL99nXvGcLgionvJl0Eg21HrRYRqn4inxxc9sCkocQtWQCZjCYGxFmEe8ony9rwb30oE4XO6QiRFeuatY27PsxJVWYAoXj8QW0VHE4Umzr3GFg="
  - secure: "VaigSzZugnvqfLWJt9AeaNHWXa/faAs9MKLSMbmfZJq5tohtTaaKv77JveTUpDsZNubjnq410hV4ZMwUgiFjrlqPZJxX5BzMNvFTIwA+0RPgtQUfNoRHAHrK3itAqjHeZ59f0gpFgpR7kVzvg4dJF7zWoFvSAscffDAS2QVyLKo="
  - secure: GVFTMs8TGOunR+eNR7VCQNkKVDWtCZ6siyB2KfgPPzeRKduUFhJA5VhhV+Vl+uhmL3767nM8Tv+ypX7C6mg2qZNcm9EJkAZzXg4f5qQJjTfxXC6lJfBn3i0S1Q9qBhwyQ1Jx+mHfth3TTXEq8sBgTuZcu+G0V8Lb4zzr83bLxto=
  matrix:
  - IDARG=1
  # disabled until I can add my ios test device
  # - IDARG=2
notifications:
  irc:
    channels:
      - "chat.freenode.net#gmusicapi"
    on_success: change
    on_failure: change
    skip_join: true
